from __future__ import annotations

import json

from agentkube_mini import Runtime, TaskGraph, auto_agent
from agentkube_mini.events import EventBus


class LegacyResearchService:
    def fetch(self, topic: str) -> dict[str, object]:
        return {
            "topic": topic,
            "facts": [
                "Legacy service call works",
                "Adapter keeps old code unchanged",
                "DAG controls execution order",
            ],
        }


class LegacyWriterService:
    def draft(self, topic: str, summary: str) -> str:
        return f"Topic={topic}\nSummary={summary}\nDraft=Generated by legacy writer"


def build_integration_graph() -> TaskGraph:
    research_service = LegacyResearchService()
    writer_service = LegacyWriterService()

    research = auto_agent("research", research_service.fetch)

    def analyze(topic: str, dependencies: dict[str, object]) -> dict[str, str]:
        research_output = dependencies["research"]
        return {
            "summary": f"{len(research_output['facts'])} facts analyzed",
            "topic": research_output["topic"],
        }

    analysis = auto_agent("analysis", analyze)

    def write(topic: str, dependencies: dict[str, object]) -> str:
        analysis_output = dependencies["analysis"]
        return writer_service.draft(
            topic=analysis_output["topic"],
            summary=analysis_output["summary"],
        )

    writer = auto_agent("writer", write)

    graph = TaskGraph()
    graph.add(research)
    graph.add(analysis, depends_on=["research"])
    graph.add(writer, depends_on=["analysis"])
    return graph


def main() -> None:
    graph = build_integration_graph()

    event_bus = EventBus()
    event_bus.subscribe("task_started", lambda e: print(f"start  | {e.task}"))
    event_bus.subscribe("task_completed", lambda e: print(f"done   | {e.task}"))

    result = Runtime(graph, event_bus=event_bus, max_workers=4).run("agent orchestration")

    print("\nOutputs:")
    print(json.dumps(result.outputs, indent=2))


if __name__ == "__main__":
    main()
